[build]
  # Build command for Next.js
  command = "pnpm run build"
  
  # Publish directory (Next.js output)
  publish = ".next"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--version"
    NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions_dir = ".next/server/app"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Netlify Forms are automatically detected from static HTML forms

